keys:
  - &pc-wwd age1v3ryu5e0ylwu9qz05s0qwa49u55m7pv4xlmmtgjn092wf782vd7qkt6ynh

creation_rules:
  - path_regex: hosts/pc-wwd/secrets\.yaml$
    key_groups:
      - age:
          - *pc-wwd
  - path_regex: hosts/pc-portatil/secrets\.yaml$
    key_groups:
      - age:
          - *pc-wwd
