[[repos]]
repo = "local"

hooks = [
  # ==========================================================
  # PRE-COMMIT
  # ==========================================================

  {
    id = "deadnix",
    name = "deadnix",
    entry = "deadnix",
    language = "system",
    files = "\\.nix$",
    pass_filenames = true
  },

  {
    id = "statix",
    name = "statix",
    entry = "statix check",
    language = "system",
    files = "\\.nix$",
    pass_filenames = false
  },

  {
    id = "alejandra",
    name = "alejandra",
    entry = "alejandra",
    language = "system",
    files = "\\.nix$",
    pass_filenames = true
  },

  # ==========================================================
  # COMMIT-MSG
  # ==========================================================

  {
    id = "commit-message",
    name = "commit message",
    entry = "scripts/ci/validate-local-commit-msg",
    language = "system",
    stages = ["commit-msg"],
    pass_filenames = true
  },

  # ==========================================================
  # PRE-PUSH
  # ==========================================================

  {
    id = "nix-flake-check",
    name = "nix flake check",
    entry = "nix flake check",
    language = "system",
    stages = ["pre-push"],
    pass_filenames = false
  }
]
