ZSH="$HOME/.oh-my-zsh"
SSH_AUTH_SOCK=$HOME/.bitwarden-ssh-agent.sock
PATH="$PATH:/opt/nvim-linux-x86_64/bin"
PATH="$PATH:$HOME/.local/bin"
ANSIBLE_BECOME_EXE=sudo.ws

AUTOSWITCH_DEFAULT_ENV="base"  # Le dice que el entorno por defecto es base
AUTOSWITCH_SILENT=1           # Silencia los mensajes

# Definir Neovim como editor global
EDITOR="nvim"
VISUAL="nvim"
